---
version: 2.1

jobs:
  build:
    docker:
    - image: circleci/golang:1.11

    steps:
    - checkout
    - run: sed -i -e 's/multimfi/vonneudeck/g' cmd/*/*.go
    - run: make
    - run: file bot-daemon
    - persist_to_workspace:
        root: .
        paths:
        - bot-daemon
    - store_artifacts:
        path: bot-daemon

  release:
    docker:
    - image: circleci/golang:1.11

    steps:
    - run: sudo apt-get update
    - run: sudo apt-get -y install fakeroot
    - run: mkdir -v -p ${HOME}/bin
    - run: curl -L 'https://github.com/aktau/github-release/releases/download/v0.7.2/linux-amd64-github-release.tar.bz2' | tar xvjf - --strip-components 3 -C ${HOME}/bin
    - attach_workspace:
        at: .
    - run: fakeroot tar -czvf ../bot-${CIRCLE_TAG}.amd64.tar.gz bot-daemon
    - run: 
        for tarfile in bot-*.tar.gz ; do
          ${HOME}/bin/github-release upload \
            --user "${CIRCLE_PROJECT_USERNAME}" \
            --repo "${CIRCLE_PROJECT_REPONAME}" \
            --tag "${CIRCLE_TAG}" \
            --name "${tarfile}" \
            --file "${tarfile}"
        done

workflows:
  version: 2
  earl:
    jobs:
    - build:
        filters:
          tags:
            only: /.*/
    - release:
        requires:
        - build
        filters:
          tags:
            only: /^v.*/
          branches:
            ignore: /.*/
